# Generated by Django 5.1.6 on 2025-02-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposithistory',
            old_name='total_deposit',
            new_name='total_deposits',
        ),
    ]
