# Generated by Django 5.1.6 on 2025-02-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_total_deposit_deposithistory_total_deposits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposithistory',
            old_name='total_deposits',
            new_name='total_deposit',
        ),
    ]
